{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "a0c0e6a2-e4d0-4f94-b1d3-493fb9c8b3cc",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>id</th>\n",
       "      <th>disaster_number</th>\n",
       "      <th>db_physical_damage_number</th>\n",
       "      <th>db_eidl_damage_number</th>\n",
       "      <th>physical_damage_number</th>\n",
       "      <th>eidl_damage_number</th>\n",
       "      <th>major_event</th>\n",
       "      <th>disaster_description</th>\n",
       "      <th>disaster_initiator</th>\n",
       "      <th>primary_disaster_state</th>\n",
       "      <th>...</th>\n",
       "      <th>naics_code_set</th>\n",
       "      <th>interest_rate</th>\n",
       "      <th>document_data</th>\n",
       "      <th>documents</th>\n",
       "      <th>major_event_display</th>\n",
       "      <th>source</th>\n",
       "      <th>source_external_files</th>\n",
       "      <th>is_ulp_serviced</th>\n",
       "      <th>is_physical_available</th>\n",
       "      <th>search_map_url</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>347da25a-ac1b-47b2-b0cf-6a81509a86ba</td>\n",
       "      <td>IN-20022</td>\n",
       "      <td>21807.0</td>\n",
       "      <td>21808</td>\n",
       "      <td>218076</td>\n",
       "      <td>218080</td>\n",
       "      <td>None</td>\n",
       "      <td>Severe Storms, Straight-line Winds, Tornadoes,...</td>\n",
       "      <td>Governor</td>\n",
       "      <td>IN</td>\n",
       "      <td>...</td>\n",
       "      <td>None</td>\n",
       "      <td>{'DL_NP': {'low_rate': 3.625, 'high_rate': 3.6...</td>\n",
       "      <td>{'605-Package': {'documents': ['a5160e6b-6a5e-...</td>\n",
       "      <td>[]</td>\n",
       "      <td>None</td>\n",
       "      <td>ULP</td>\n",
       "      <td>[]</td>\n",
       "      <td>True</td>\n",
       "      <td>True</td>\n",
       "      <td>None</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>6ae460cd-a7ce-4fbe-a24a-f82c7358da36</td>\n",
       "      <td>PA-20040</td>\n",
       "      <td>21793.0</td>\n",
       "      <td>21794</td>\n",
       "      <td>21793B</td>\n",
       "      <td>217940</td>\n",
       "      <td>None</td>\n",
       "      <td>Severe Storms and Flooding</td>\n",
       "      <td>Governor Josh Shapiro</td>\n",
       "      <td>PA</td>\n",
       "      <td>...</td>\n",
       "      <td>None</td>\n",
       "      <td>{'DL_NP': {'low_rate': 3.625, 'high_rate': 3.6...</td>\n",
       "      <td>{'605-Package': {'documents': ['d55724d9-218a-...</td>\n",
       "      <td>[{'id': '10986958-28d2-45f5-9357-6dd4f2b0893e'...</td>\n",
       "      <td>None</td>\n",
       "      <td>ULP</td>\n",
       "      <td>[]</td>\n",
       "      <td>True</td>\n",
       "      <td>True</td>\n",
       "      <td>None</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>656f8851-821c-4495-98ed-6dff5bb40544</td>\n",
       "      <td>IL-20035</td>\n",
       "      <td>21790.0</td>\n",
       "      <td>21791</td>\n",
       "      <td>21790B</td>\n",
       "      <td>217910</td>\n",
       "      <td>None</td>\n",
       "      <td>Severe Storms</td>\n",
       "      <td>Governor JB Pritzker</td>\n",
       "      <td>IL</td>\n",
       "      <td>...</td>\n",
       "      <td>None</td>\n",
       "      <td>{'DL_NP': {'low_rate': 3.625, 'high_rate': 3.6...</td>\n",
       "      <td>{'605-Package': {'documents': ['800d44cd-43fe-...</td>\n",
       "      <td>[{'id': '4d2560e6-34ad-4ce1-9b87-010d658265c1'...</td>\n",
       "      <td>None</td>\n",
       "      <td>ULP</td>\n",
       "      <td>[]</td>\n",
       "      <td>True</td>\n",
       "      <td>True</td>\n",
       "      <td>None</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>32a15e3c-df65-41b3-968f-1e7f0bc6c095</td>\n",
       "      <td>WV-20027</td>\n",
       "      <td>21751.0</td>\n",
       "      <td>21752</td>\n",
       "      <td>21751B</td>\n",
       "      <td>217520</td>\n",
       "      <td>None</td>\n",
       "      <td>Severe Storms, Straight-line Winds, Tornadoes,...</td>\n",
       "      <td>Governor Patrick Morrisey</td>\n",
       "      <td>WV</td>\n",
       "      <td>...</td>\n",
       "      <td>None</td>\n",
       "      <td>{'DL_NP': {'low_rate': 3.625, 'high_rate': 3.6...</td>\n",
       "      <td>{'605-Package': {'documents': ['2d686441-8c0c-...</td>\n",
       "      <td>[{'id': 'c0493547-505f-4e48-a0e8-12faac0f1654'...</td>\n",
       "      <td>None</td>\n",
       "      <td>ULP</td>\n",
       "      <td>[]</td>\n",
       "      <td>True</td>\n",
       "      <td>True</td>\n",
       "      <td>None</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>f3672271-5cc5-48b1-b250-788bcd6d4ebd</td>\n",
       "      <td>PA-20038</td>\n",
       "      <td>21737.0</td>\n",
       "      <td>21738</td>\n",
       "      <td>21737B</td>\n",
       "      <td>217380</td>\n",
       "      <td>None</td>\n",
       "      <td>Severe Storms</td>\n",
       "      <td>Governor Josh Shapiro</td>\n",
       "      <td>PA</td>\n",
       "      <td>...</td>\n",
       "      <td>None</td>\n",
       "      <td>{'DL_NP': {'low_rate': 3.625, 'high_rate': 3.6...</td>\n",
       "      <td>{'605-Package': {'documents': ['e562ca2a-7ec2-...</td>\n",
       "      <td>[{'id': 'bade37ad-6fd7-4e29-b8b1-def73d466670'...</td>\n",
       "      <td>None</td>\n",
       "      <td>ULP</td>\n",
       "      <td>[]</td>\n",
       "      <td>True</td>\n",
       "      <td>True</td>\n",
       "      <td>None</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "<p>5 rows × 48 columns</p>\n",
       "</div>"
      ],
      "text/plain": [
       "                                     id disaster_number  \\\n",
       "0  347da25a-ac1b-47b2-b0cf-6a81509a86ba        IN-20022   \n",
       "1  6ae460cd-a7ce-4fbe-a24a-f82c7358da36        PA-20040   \n",
       "2  656f8851-821c-4495-98ed-6dff5bb40544        IL-20035   \n",
       "3  32a15e3c-df65-41b3-968f-1e7f0bc6c095        WV-20027   \n",
       "4  f3672271-5cc5-48b1-b250-788bcd6d4ebd        PA-20038   \n",
       "\n",
       "   db_physical_damage_number  db_eidl_damage_number physical_damage_number  \\\n",
       "0                    21807.0                  21808                 218076   \n",
       "1                    21793.0                  21794                 21793B   \n",
       "2                    21790.0                  21791                 21790B   \n",
       "3                    21751.0                  21752                 21751B   \n",
       "4                    21737.0                  21738                 21737B   \n",
       "\n",
       "  eidl_damage_number major_event  \\\n",
       "0             218080        None   \n",
       "1             217940        None   \n",
       "2             217910        None   \n",
       "3             217520        None   \n",
       "4             217380        None   \n",
       "\n",
       "                                disaster_description  \\\n",
       "0  Severe Storms, Straight-line Winds, Tornadoes,...   \n",
       "1                         Severe Storms and Flooding   \n",
       "2                                      Severe Storms   \n",
       "3  Severe Storms, Straight-line Winds, Tornadoes,...   \n",
       "4                                      Severe Storms   \n",
       "\n",
       "          disaster_initiator primary_disaster_state  ... naics_code_set  \\\n",
       "0                   Governor                     IN  ...           None   \n",
       "1      Governor Josh Shapiro                     PA  ...           None   \n",
       "2       Governor JB Pritzker                     IL  ...           None   \n",
       "3  Governor Patrick Morrisey                     WV  ...           None   \n",
       "4      Governor Josh Shapiro                     PA  ...           None   \n",
       "\n",
       "                                       interest_rate  \\\n",
       "0  {'DL_NP': {'low_rate': 3.625, 'high_rate': 3.6...   \n",
       "1  {'DL_NP': {'low_rate': 3.625, 'high_rate': 3.6...   \n",
       "2  {'DL_NP': {'low_rate': 3.625, 'high_rate': 3.6...   \n",
       "3  {'DL_NP': {'low_rate': 3.625, 'high_rate': 3.6...   \n",
       "4  {'DL_NP': {'low_rate': 3.625, 'high_rate': 3.6...   \n",
       "\n",
       "                                       document_data  \\\n",
       "0  {'605-Package': {'documents': ['a5160e6b-6a5e-...   \n",
       "1  {'605-Package': {'documents': ['d55724d9-218a-...   \n",
       "2  {'605-Package': {'documents': ['800d44cd-43fe-...   \n",
       "3  {'605-Package': {'documents': ['2d686441-8c0c-...   \n",
       "4  {'605-Package': {'documents': ['e562ca2a-7ec2-...   \n",
       "\n",
       "                                           documents major_event_display  \\\n",
       "0                                                 []                None   \n",
       "1  [{'id': '10986958-28d2-45f5-9357-6dd4f2b0893e'...                None   \n",
       "2  [{'id': '4d2560e6-34ad-4ce1-9b87-010d658265c1'...                None   \n",
       "3  [{'id': 'c0493547-505f-4e48-a0e8-12faac0f1654'...                None   \n",
       "4  [{'id': 'bade37ad-6fd7-4e29-b8b1-def73d466670'...                None   \n",
       "\n",
       "  source source_external_files  is_ulp_serviced  is_physical_available  \\\n",
       "0    ULP                    []             True                   True   \n",
       "1    ULP                    []             True                   True   \n",
       "2    ULP                    []             True                   True   \n",
       "3    ULP                    []             True                   True   \n",
       "4    ULP                    []             True                   True   \n",
       "\n",
       "  search_map_url  \n",
       "0           None  \n",
       "1           None  \n",
       "2           None  \n",
       "3           None  \n",
       "4           None  \n",
       "\n",
       "[5 rows x 48 columns]"
      ]
     },
     "execution_count": 1,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "import requests\n",
    "import pandas as pd\n",
    "\n",
    "url = \"https://lending.sba.gov/api/disasters/v1/declarations/\"\n",
    "\n",
    "response = requests.get(url)\n",
    "\n",
    "data = response.json()\n",
    "\n",
    "df = pd.DataFrame(data)\n",
    "\n",
    "df.head()\n"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.11.13"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
